#!/bin/bash

plojo="/Users/hui/Documents/Scripts/plojo_app/plojo"
plojonior="/Users/hui/Documents/Scripts/plojo_app/plojo-nior"
simuojo="/Users/hui/Documents/Scripts/plojo_app/simuojo"
foldojo="/Users/hui/Documents/Scripts/plojo_app/foldojo"
plojohelp="/Users/hui/Documents/Scripts/plojo_app/plojo_help"
menu="$plojo $plojonior $simuojo $foldojo $plojohelp"
menuarr=($menu)


echo ""
echo "***************************"
echo "*    Start Plojo Server   *"
echo "***************************"
option=100

while true;
do
echo""
echo "Choose option:"
echo "1. plojo"
echo "2. plojo-nior"
echo "3. simuojo"
echo "4. foldojo"
echo "5. plojo help"
echo "0. exit"

read option
if [ $option = 0 ]
then
break
elif (( $option > 5 )) 
then
echo "Your selection $option is not at service."
continue
fi
echo "Your option is $option : ${menuarr[$option-1]} "
echo ""
bokeh serve ${menuarr[$option-1]} --show

done

echo "Byebye!"

#if [ $option = 1 ]
#then
#echo "Start plojo server:"
#bokeh serve $plojo --show
#elif [ $option = 2 ]
#then
#echo "Start plojo-nior server:"
#bokeh serve $plojonior --show
#fi





#bokeh serve /Users/hui/Documents/Scripts/plojo_app/simuojo /Users/hui/Documents/Scripts/plojo_app/plojo /Users/hui/Documents/Scripts/plojo_app/plojo-nior --show
