#!/bin/bash

echo ""
echo "***************************"
echo "*    Start Plojo Server   *"
echo "***************************"

bokeh serve /Users/hui/Work/Scripts/plojo_app/plojo /Users/hui/Work/Scripts/plojo_app/plojo-nior /Users/hui/Work/Scripts/plojo_app/simuojo --show
